env:
 - GHCVER=7.0.1
 - GHCVER=7.0.2
 - GHCVER=7.0.3
 - GHCVER=7.0.4
 - GHCVER=7.2.1
 - GHCVER=7.2.2
 - GHCVER=7.4.1
 - GHCVER=7.4.2
 - GHCVER=7.6.1
 - GHCVER=7.6.2
 - GHCVER=7.6.3
 - GHCVER=7.8.1
 - GHCVER=7.8.2
 - GHCVER=7.8.3

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER # see note about happy/alex
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.18/bin:$PATH
 - |
   if [ $GHCVER = "head" ] || [ ${GHCVER%.*} = "7.8" ]; then
     travis_retry sudo apt-get install happy-1.19.4 alex-3.1.3
     export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH
   else
     travis_retry sudo apt-get install happy alex
   fi
 - |
   if [ ${GHCVER%.*} != "7.0" ]; then
     export CONFIGURE_OPTS="--enable-tests"
     export DO_TEST="cabal test"
   fi

install:
 - cabal update
 - cabal install --only-dependencies --enable-tests

script:
 - cabal configure $CONFIGURE_OPTS -v2
 - cabal build
 - $DO_TEST
 - cabal check
 - cabal sdist

# The following scriptlet checks that the resulting source distribution can be built & installed
 - export SRC_TGZ=$(cabal-1.18 info . | awk '{print $2 ".tar.gz";exit}') ;
   cd dist/;
   if [ -f "$SRC_TGZ" ]; then
      cabal install "$SRC_TGZ";
   else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
   fi
